### ISSUE TITLE
Fails to merge trx that contains tests which have the same id

### ISSUE THREAD

**Issue by samholder** [ricardofslp/dotnet-trx-merge#36]
Hi. 

I have been doing the trx merge process manually, but I like the idea of this tool and have been switching some builds to use it. thanks for this.

Unfortunately we have some tests that use MSTest data driven tests which use the [ITestDataSource](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.itestdatasource?view=visualstudiosdk-2022) on an attribute in the tests, and this results in a trx where some tests have the same id, and this causes the tool to blow up when getting the test entry:

    private XElement GetTestEntry(IEnumerable<XElement> entries, string testId)
        => entries.SingleOrDefault(entry => entry.Attribute("testId")!.Value.Equals(testId))!;
        
  As there is more than 1 entry here.
  
  I am happy to look at a fix for this issue and to create a PR but want to check that you would be open to merging this change if I do.

**Comment by samholder** [comment]
I plan to create a TestIdentity object which encapsulates the id and the name to use to match the tests, rather than just using the id as it does now

**Comment by ricardofslp** [comment]
Hi @samholder,

Thanks for reporting this.
I would be open to merge in order to improve this tool since this is a use case that makes sense.

If you don't have the time to do the PR just let me know that I will work on that myself.

Best Regards

**Comment by samholder** [comment]
Great, I'll create a PR, hopefully this evening, with some example test data that fails as a starting point and hopefully a fix shortly afterwards

**Comment by ricardofslp** [comment]
I will have some time tomorrow to look at this so, if you cannot open the PR with the fix, please share with me some files with examples that cause issues.

This way I can see the issue easier and think of a solution and even add this scenario to the tests.

**Comment by samholder** [comment]
I will have a WIP PR for this available shortly. I struggled yesterday to find a consistent way of reproducing the same id issue, and raised a question https://github.com/microsoft/testfx/issues/1744 to try understand how it works. In the mean time will have an example file from a real run to show the issue. I have a basic fix in place I think but need to complete adding the tests.

Hopefully this will be available in the next few hours. thanks for being so keen to fix this!

**Comment by samholder** [comment]
https://github.com/ricardofslp/dotnet-trx-merge/pull/37

**Comment by ricardofslp** [comment]
Thank you very much for the help on this @samholder.
Yesterday I also tried to reproduce the issue but was having issues with it.

**Comment by ricardofslp** [comment]
@samholder can you please try this alpha version https://www.nuget.org/packages/dotnet-trx-merge/1.2.0-alpha.0 with the change to see if it now works?

**Comment by samholder** [comment]
Yes I'll have a go tonight. 

Thanks for three quick response

**Comment by samholder** [comment]
yep, that seems to work now!

thanks a lot for getting a new version out so quickly!

**Comment by ricardofslp** [comment]
Released now the official version.
Thanks for the help
