### ISSUE TITLE
Allow merge to work and preserve the namespaces

### ISSUE THREAD

**Issue by samholder** [ricardofslp/dotnet-trx-merge#42]
Hi,

Is there a reason not to stop stripping the namespaces and to preserve them on the TestRun element in the result?

I think it would be better to make the output as trx like as possible.

I have a branch which I have started adding this functionality and would happily raise a PR to add this, if you are up for it.

Currently the TrxMerger takes an XDocument but I'm thinking it would be better to allow it to create the XDocument and set the correct id (reuse one, or generate a new one?) copy the name and runUser from the first file, set the times from the first file + adjust the start and end times to  be earliest and the latest end time from any of the files.

**Comment by samholder** [comment]
We could keep the existing method signature and pass in the XDocument but adjust it to have a namespace first

**Comment by ricardofslp** [comment]
Hi @samholder,

The XDocument received is actually created as blank in a previous step.

Regarding the namespaces the strip of it was added in this PR https://github.com/ricardofslp/dotnet-trx-merge/pull/30

Please open the PR for this if you can

**Comment by samholder** [comment]
yep, leave it with me, I'll fix this over the weekend if I don't get time today.

**Comment by samholder** [comment]
PR created. Let me know if you want me to test a pre release version (I'm hoping this fixes warnings we get in our pipelines)

**Comment by ricardofslp** [comment]
Please test with this alpha version: https://www.nuget.org/packages/dotnet-trx-merge/1.3.0-alpha.0

**Comment by samholder** [comment]
apologies I've not had chance to test with this yet, I'm hoping to get to it today

**Comment by samholder** [comment]
finally got round to testing this and it all seems good!

**Comment by ricardofslp** [comment]
Hi @samholder,

Thanks for the test. 
Will release the official version soon.

**Comment by ricardofslp** [comment]
New version released.
Please check and close the issue if ok

**Comment by samholder** [comment]
all looks good
