### ISSUE TITLE
Merged TRX's don't open in Visual Studio

### ISSUE THREAD

**Issue by thenutter** [ricardofslp/dotnet-trx-merge#72]
Any TRX that I combine can't be opened within Visual Studio, is anybody else seeing this issue?

It seems to be because the '_TestRun_' node has all its elements removed, when I add them back in it seems to work well.

Thanks so much for making this!

**Comment by ricardofslp** [comment]
Hi @thenutter,

Will try to take a look into this in the next weekend. To see if I can make it open on vs.

**Comment by thenutter** [comment]
Amazing, thanks!

**Comment by ricardofslp** [comment]
Hi @thenutter,

Can you try with this version https://www.nuget.org/packages/dotnet-trx-merge/1.4.0-alpha.0 ?

**Comment by martin-nutter** [comment]
Hi @ricardofslp

Thanks for looking into this.

I've tested with Visual Studio 2019 & Visual Studio 2022 and both no longer show an object reference error - but show no tests:

![image](https://github.com/ricardofslp/dotnet-trx-merge/assets/88317912/232b5c81-6139-44c5-8733-9db4d49e79b5)

And Txer isn't able to produce a report (https://github.com/NivNavick/trxer):

![image](https://github.com/ricardofslp/dotnet-trx-merge/assets/88317912/37b53d89-20f3-4934-890d-9d18eb08e0d5)

I've tested with both merging TRX's with duplicate tests, and ones with no duplicates and both show the same results.

**Comment by martin-nutter** [comment]
@ricardofslp - it looks like a few of the xmlns= attributes are null.

Fixing those up by hand to:
_  <TestEntries xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">_

seems to work

**Comment by ricardofslp** [comment]
Hi @martin-nutter, 

So it's the lack of the attribute xmlns that is causing you issues?
In which entries have you added that manually?

**Comment by martin-nutter** [comment]
So the test run attributes you added along with replacing all empty xmlns's solves the issue for me and the files work in all visual studios which is fantastic.

After the merge I now do:
`(Get-Content combined.trx) -replace 'xmlns=""', 'xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010"' | Set-Content combined.trx`

and it works, so I guess all xmlns's need to be populated.

**Comment by ricardofslp** [comment]
Hi @thenutter ,

It doesn't work for all tools since I've had requests in the past to remove those.
Probably I will add an option to copy the namespaces (to be backwards compatible).

**Comment by KurtYilmaz** [comment]
Reporting the same! Removing all instances of `xmlns=""` fixes the issue. Would love an option to remove that bit from the nodes

**Comment by ricardofslp** [comment]
Hi @KurtYilmaz ,

In your scenario the merge is bringing the xmlns and causing issues? The original problem reported was in fact the lack of it.

Thanks.

Ricardo Pereira

**Comment by KurtYilmaz** [comment]
Hi @ricardofslp! Yeah, it's the blank xmlns that's causing the problems, but it's fixed with a find and replace like the one that @martin-nutter posted. It looks like it was also reported in #77

**Comment by martin-nutter** [comment]
@ricardofslp - Any update on this, I think for it to work on Visual Studio we need the xmlns's populated. Which reporting tools don't like this being populated?

**Comment by ricardofslp** [comment]
Sorry @martin-nutter and @KurtYilmaz ,

I had no change to work on this but will do that in the next days.

**Comment by KurtYilmaz** [comment]
No problem! Thanks for maintaining this

**Comment by ricardofslp** [comment]
Hi,

There is a new optional argument called --namespace or -n that will allow to do a replace of the namespace in the output file.
Can you please try to call this by using this argument and providing the namespace that you want?

This is available in version: https://www.nuget.org/packages/dotnet-trx-merge/1.4.0-alpha.1

**Comment by ricardofslp** [comment]
Hi @martin-nutter and @KurtYilmaz ,

Have you tried the newest versions?
