### ISSUE TITLE
This tool adds empty xmlnamespaces

### ISSUE THREAD

**Issue by mwwhited** [ricardofslp/dotnet-trx-merge#77]
This tool incorrectly recreates the XML files by changing namespaces from `xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010"` to `xmlns=""`

**Comment by ricardofslp** [comment]
Hi,

There is a new optional argument called --namespace or -n that will allow to do a replace of the namespace in the output file.
Can you please try to call this by using this argument and providing the namespace that you want?

This is available in version: https://www.nuget.org/packages/dotnet-trx-merge/1.4.0-alpha.1

**Comment by ricardofslp** [comment]
Hi @mwwhited ,

Have you tried the newer version to see if it works?
