### ISSUE TITLE
NullReferenceException thrown when runUser missing

### ISSUE THREAD

**Issue by mullerj** [ricardofslp/dotnet-trx-merge#97]
dotnet_trx_merge.Services.TrxFetcher.FetchOnlyLatest(String[] filesToMerge) throws NullReferenceException when runUser attribute is missing from the root element.

**Comment by samholder** [comment]
I've noticed this has started recently, and I think its mstest no longer adding this user to the trx

anyway, I've created a PR to address this and default the  runUser if its not found

**Comment by ricardofslp** [comment]
Hi @mullerj,

Thanks for reporting this.

@samholder thanks for the PR I will take a look

**Comment by ricardofslp** [comment]
Hi @mullerj,

Please test version: https://www.nuget.org/packages/dotnet-trx-merge/2.0.1
Please provide feedback to see if we can close the issue

**Comment by samholder** [comment]
This looks like it works to me, I see the warning output when I run this in my devops pipeline and merge happens now.

thanks for the quick merge and new version @ricardofslp

**Comment by mullerj** [comment]
I tested with a trx file that is missing the runUser attribute and NullReferenceException is no longer thrown.
